        
            <div id="bgimg-error">
                <nav id="mySidenav" class="sidenav">
                    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                    <ul>
                        <li><a href="/" class="link">Home</a></li>
                        <li><a href="/portfolio" class="link">Portfolio</a></li>
                    </ul>
                </nav>
                <span id="menuIcon" onclick="openNav()">&#9776;</span>
                <span id = "menu" onclick="openNav()">Menu</span>
                <div class="caption">
                    <p class="typewrite" data-period="2000" data-type='[ "Opps! Page not found."]'>
                    <span class="wrap"></span>
                    <ul>
                        <li><a href="/" class="active">Home</a></li>
                        <li><a href="/portfolio" class="home_link">Portfolio</a></li>
                    </ul>
                </div>
        
            </div>
            

        