            <div id="bgimg-1">
                <nav id="mySidenav" class="sidenav">
                    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                    <ul>
                        <li><a href="/" class="link">Home</a></li>
                        <li><a href="/portfolio" class="link">Portfolio</a></li>
                    </ul>
                </nav>
                <span id="menuIcon" onclick="openNav()">&#9776;</span>
                <span id = "menu" onclick="openNav()">Menu</span>
                <div class="caption">
                    <p class="typewrite" data-period="2000" data-type='[ "Hi! My name is Ryan", "I am very motivated person.", "I am Creative.", "I Love to Design.", "I Love to Develop."]'>
                    <span class="wrap"></span>
                    <ul>
                        <li><a href="/portfolio" class="active">SEE MY PORTFOLIO</a></li>
                        <li><a href="#" id="click1" class="home_link">LEARN MORE ABOUT ME</a></li>
                    </ul>
                </div>
                <a href="#" id ="click"><img src = "img/down_arrow.png" id ="scroll"/></a>
            </div>

        <div id = "content1">
            <h3 id ="nextpage" class ="heading1">About Me</h3>
            <p>My name is Ryan T. Belandres, I’m a Filipino and I’m proud of it. Currently I’ m studying at British Columbia Institute of Technology (BCIT) as a web developer. I would describe myself as a very determined and highly motivated person. I do take job seriously but I'm able to see things in perspective and believe I'm quite easy-going to work with. I am an easy-going person and don’t get easily disturbed by down’s in my life. I love watching survival videos, hiking, and having great intellectual conversations! I love giving trivia about science and animal facts. Feel free to have a look at my portfolio and don't hesitate to contact me if you think I can be of service to you. 
            </p>
        </div>
        <div class="pics">
                <img class="pics_profile" src="img/pics4.jpg">
                <img class="pics_profile" src="img/pics3.jpg">
                <img class="pics_profile" src="img/pics5.jpg">
                <img class="pics_profile" src="img/profile.jpg">
                <img class="pics_profile" src="img/pics2.jpg">
                <img class="pics_profile" src="img/pics1.jpg">
        </div>
        <div id="bgimg-2">
                <h2>Educations</h2>
                <div class = "edu">
                    <p><strong>British Columbia Institute of Technology</strong></p>
                    <p>Computer Systems Technology (Diploma).</p>
                    <p>July 2017 - Present</p>
                </div>
                <div class = "edu">
                    <p><strong>British Columbia Institute of Technology</strong></p>
                    <p>Applied Web Development (Certificate) with distinction.</p>
                    <p>January 2016 - July 2017</p>
                </div>
                <div class = "edu">
                    <p><strong>University Of Mindanao</strong></p>
                    <p>Bachelor of Science in Information Technology (Undergraduate).</p>
                    <p>June 2009 - February 2012</p>
                </div>
                <div class = "edu">
                    <p><strong>Emilio Ramos National High School</strong></p>
                    <p>2004 - 2008</p>
                </div>
        </div>

        <div id="quotes">
                <p>"It always seems impossible until its done."</p>
                <p>-Nelson Mandela</p>
        </div>

        <div id="bgimg-3">
                <div id="skill_con">
                    <h2>Skills</h2>
                    <p>'This project is created using MVC pattern and ZEND framework'</p>
                    <span class="skill">HTML <img src="img/five.png"/></span>
                    <span class="skill">CSS <img src="img/four.png"/></span>
                    <span class="skill">Javascript <img src="img/three.png"/></span>
                    <span class="skill">Jquery <img src="img/two.png"/></span>
                    <span class="skill">PHP <img src="img/three.png"/></span>
                    <span class="skill">MVC <img src="img/three.png"/></span>
                    <span class="skill">ZEND Framework <img src="img/two.png"/></span>
                    <span class="skill">SQL <img src="img/three.png"/></span>
                    <span class="skill">UX/UI <img src="img/four.png"/></span>
                    <span class="skill">Wordpress <img src="img/three.png"/></span>
                    <span class="skill">Java <img src="img/three.png"/></span>
                    <span class="skill">Angular js <img src="img/three.png"/></span>
                    <span class="skill">Vue.js <img src="img/two.png"/></span>
                    <span class="skill">Ionic framework <img src="img/two.png"/></span>
                    <h2>languages</h2>
                    <span class="skill">Visaya <img src="img/five.png"/></span>
                    <span class="skill">Tagalog <img src="img/five.png"/></span>
                    <span class="skill">English <img src="img/four.png"/></span>
                    <span class="skill">Spanish <img src="img/one.png"/></span>
                    <h2>Tools</h2>
                    <span class="skill">Photoshop <img src="img/four.png"/></span>
                    <span class="skill">Lightroom <img src="img/four.png"/></span>
                    <span class="skill">Experience Design <img src="img/four.png"/></span>
                    <span class="skill">Photomatix pro <img src="img/five.png"/></span>
                    <span class="skill">FileZilla <img src="img/five.png"/></span>
                    <span class="skill">TextWrangler pro <img src="img/five.png"/></span>
                    <span class="skill">Sublime Text<img src="img/five.png"/></span>
                    <span class="skill">Bluej <img src="img/five.png"/></span>
                    <span class="skill">Eclipse <img src="img/four.png"/></span>
                    <span class="skill">Mac <img src="img/five.png"/></span>
                    <span class="skill">Windows <img src="img/five.png"/></span>
                    <span class="skill">MS Word <img src="img/four.png"/></span>
                    <span class="skill">MS Powerpoint <img src="img/four.png"/></span>   
                </div>  
        </div>