            <div id="bgimg-4">
            <!-- make the lights in the bg blink link http://jsfiddle.net/r6dje/-->
                <nav id="mySidenav" class="sidenav">
                    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                    <ul>
                        <li><a href="/" class="link">Home</a></li>
                        <li><a href="/portfolio" class="link">Portfolio</a></li>
                    </ul>
                </nav>
                <span id="menuIcon" onclick="openNav()">&#9776;</span>
                <span id = "menu" onclick="openNav()">Menu</span>
                <div class="caption">
                    <p class="typewrite" data-period="2000" data-type='[ "Hi! Im Ryan", "I am Creative.", "I Love Design.", "I Love to Develop."]'>
                    <span class="wrap"></span>
                    <ul>
                        <li><a href="#" id="click1" class="active">SEE MY PORTFOLIO</a></li>
                        <li><a href="/" class="home_link">LEARN MORE ABOUT ME</a></li>
                    </ul>
                </div>
                <a href="#" id ="click"><img src = "img/scroll.png" id ="scroll"/></a>
            </div>

<div id="gallery">
    <span id="nextpage"></span>
    <img src="/gallery/5065071803.jpg" onclick="openModal();currentSlide(1)">
    <img src="/gallery/5065071804.jpg" onclick="openModal();currentSlide(2)">
    <img src="/gallery/5065071805.jpg" onclick="openModal();currentSlide(3)">
    <img src="/gallery/5065071806.jpg" onclick="openModal();currentSlide(4)">
    <img src="/gallery/5065071807.jpg" onclick="openModal();currentSlide(5)">
    <img src="/gallery/5065071808.jpg" onclick="openModal();currentSlide(6)">
    <img src="/gallery/5065071809.jpg" onclick="openModal();currentSlide(7)">
    <img src="/gallery/50650718011.jpg" onclick="openModal();currentSlide(8)">
    <img src="/gallery/50650718012.jpg" onclick="openModal();currentSlide(9)">
    <img src="/gallery/50650718013.jpg" onclick="openModal();currentSlide(10)">
    <img src="/gallery/50650718015.jpg" onclick="openModal();currentSlide(11)">
    <img src="/gallery/50650718016.jpg" onclick="openModal();currentSlide(12)">
    <img src="/gallery/50650718017.jpg" onclick="openModal();currentSlide(13)">
    <img src="/gallery/50650718018.jpg" onclick="openModal();currentSlide(14)">
    <img src="/gallery/50650718019.jpg" onclick="openModal();currentSlide(15)">
    <img src="/gallery/50650718020.jpg" onclick="openModal();currentSlide(16)">
    <img src="/gallery/iceberg2.jpg" onclick="openModal();currentSlide(17)">
    <img src="/gallery/kitesurfing.jpg" onclick="openModal();currentSlide(18)">
    <img src="/gallery/tinuyanfalls.jpg" onclick="openModal();currentSlide(19)">
    <img src="/gallery/alligator.jpg" onclick="openModal();currentSlide(20)">
    <img src="/gallery/miracle_beach.jpg" onclick="openModal();currentSlide(21)">
    <img src="/gallery/old_pipe.jpg" onclick="openModal();currentSlide(22)">
  
</div>

<div id="myModal" class="modal">
  <span class="close cursor" onclick="closeModal()">&times;</span>
  <div class="modal-content">

    <div class="mySlides">
      <div class="numbertext">1 / 22</div>
      <img src="/gallery/5065071803.jpg" style="width:100%">
      <p class="caption-container">My first digital painting using photoshop</p>
    </div>

    <div class="mySlides">
      <div class="numbertext">2 / 22</div>
      <img src="/gallery/5065071804.jpg" style="width: 100%">
      <p class="caption-container">3d effect using photoshop</p>
    </div>

    <div class="mySlides">
      <div class="numbertext">3 / 22</div>
      <img src="/gallery/5065071805.jpg" style="width: 100%">
      <p class="caption-container">Agassiz tulip festival</p>
    </div>
    
    <div class="mySlides">
      <div class="numbertext">4 / 22</div>
      <img src="/gallery/5065071806.jpg" style="width: 100%">
      <p class="caption-container">Squamish terminal on fire</p>
    </div>

    <div class="mySlides">
      <div class="numbertext">5 / 22</div>
      <img src="/gallery/5065071807.jpg" style="width: 100%">
      <p class="caption-container">Squamish terminal on fire</p>
    </div>

    <div class="mySlides">
      <div class="numbertext">6 / 22</div>
      <img src="/gallery/5065071808.jpg" style="width: 100%">
      <p class="caption-container">Vancouver city lights</p>
    </div>

    <div class="mySlides">
      <div class="numbertext">7 / 22</div>
      <img src="/gallery/5065071809.jpg" style="width: 100%">
      <p class="caption-container">Sunset in Ambleside Park</p>
    </div>

    <div class="mySlides">
      <div class="numbertext">8 / 22</div>
      <img src="/gallery/50650718011.jpg" style="width: 100%">
      <p class="caption-container">Hello frogy</p>
    </div>

    <div class="mySlides">
      <div class="numbertext">9 / 22</div>
      <img src="/gallery/50650718012.jpg" style="width: 100%">
      <p class="caption-container"></p>
    </div>

    <div class="mySlides">
      <div class="numbertext">10 / 22</div>
      <img src="/gallery/50650718013.jpg" style="width: 100%">
      <p class="caption-container">Canada day 2014</p>
    </div>

    <div class="mySlides">
      <div class="numbertext">11 / 22</div>
      <img src="/gallery/50650718015.jpg" style="width: 100%">
      <p class="caption-container">Brackendale trail in Squamish</p>
    </div>

    <div class="mySlides">
      <div class="numbertext">12 / 22</div>
      <img src="/gallery/50650718016.jpg" style="width: 100%">
      <p class="caption-container">Out of bound effect using photoshop</p>
    </div>

    <div class="mySlides">
      <div class="numbertext">13 / 22</div>
      <img src="/gallery/50650718017.jpg" style="width: 100%">
      <p class="caption-container">Out of bound effect using photoshop</p>
    </div>

    <div class="mySlides">
      <div class="numbertext">14 / 22</div>
      <img src="/gallery/50650718018.jpg" style="width: 100%">
      <p class="caption-container">Panel effect using photoshop</p>
    </div>

    <div class="mySlides">
      <div class="numbertext">15 / 22</div>
      <img src="/gallery/50650718019.jpg" style="width: 100%">
      <p class="caption-container"></p>
    </div>

    <div class="mySlides">
      <div class="numbertext">16 / 22</div>
      <img src="/gallery/50650718020.jpg" style="width: 100%">
      <p class="caption-container">Tiger Salamander</p>
    </div>

    <div class="mySlides">
      <div class="numbertext">17 / 22</div>
      <img src="/gallery/iceberg2.jpg" style="width: 100%">
      <p class="caption-container">Joffre Lake Glacier</p>
    </div>

    <div class="mySlides">
      <div class="numbertext">18 / 22</div>
      <img src="/gallery/kitesurfing.jpg" style="width: 100%">
      <p class="caption-container">Squamish kitesurfing</p>
    </div>

    <div class="mySlides">
      <div class="numbertext">19 / 22</div>
      <img src="/gallery/tinuyanfalls.jpg" style="width: 100%">
      <p class="caption-container">Tinuy-an falls Philippines</p>
    </div>

    <div class="mySlides">
      <div class="numbertext">20 / 22</div>
      <img src="/gallery/alligator.jpg" style="width: 100%">
      <p class="caption-container">Close encounter with the beast!</p>
    </div>

    <div class="mySlides">
      <div class="numbertext">21 / 22</div>
      <img src="/gallery/miracle_beach.jpg" style="width: 100%">
      <p class="caption-container">Miracle Beach</p>
    </div>

    <div class="mySlides">
      <div class="numbertext">22 / 22</div>
      <img src="/gallery/old_pipe.jpg" style="width: 100%">
      <p class="caption-container"></p>
    </div>
    
    <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
    <a class="next" onclick="plusSlides(1)">&#10095;</a>

    

    <div class="caption-container">
      <p id="caption"></p>
    </div>
    
  </div>
</div>

<script>
    function openModal() {
      document.getElementById('myModal').style.display = "block";
    }

    function closeModal() {
      document.getElementById('myModal').style.display = "none";
    }

    var slideIndex = 1;
    showSlides(slideIndex);

    function plusSlides(n) {
      showSlides(slideIndex += n);
    }

    function currentSlide(n) {
      showSlides(slideIndex = n);
    }

    function showSlides(n) {
      var i;
      var slides = document.getElementsByClassName("mySlides");
      
      if (n > slides.length) {slideIndex = 1}
      if (n < 1) {slideIndex = slides.length}
      for (i = 0; i < slides.length; i++) {
          slides[i].style.display = "none";
      }
      
      slides[slideIndex-1].style.display = "block";
      
    }
</script>










        